### PR TITLE
Deploy Image from Container Registry to Kubernetes Cluster

### LINKED ISSUE #305: [Deployment] Deploy generated Docker Image to Cluster
**Is your feature request related to a problem? Please describe.**
Once #304 is completed, we need the ability to deploy that generated image to a cluster, e.g. in Azure or AWS.

**Describe the solution you'd like**
To be discussed, but we probably want to deploy the model to a namespace within the cluster that has the name of `{ExperimentName}/{DeploymentTargetName}` or alike.

### PR DESCRIPTION
**Pull request by aslotte**
## Resolves
Fixes #305

### CODE REVIEW

**Comment by aslotte** [comment]
Improvements:
- Pass in wrapped dictionary of sorts to parameterization
- Add integration tests that tests against real Kubernetes cluster and registry?

**Comment by aslotte** [comment]
Remaining work: 
- Additional local testing to ensure it gets correctly deployed and functions
- Figure out how to pass back the service url so we can add it to the deployment object
- Add additional unit and integration tests as possible
- Add new issues for integrating with schema from DB, configuring options, kubeconfig from setting...

**Comment by aslotte** [comment]
@AnoojNair / @Brett-Parker  there' additional work on this PR still, but the skeleton is there. Do you prefer me knocking out the rest on this PR, or do you want to review it as is, merge it, and continue on a smaller PR so it's easier to follow along? Either way works for me.

**Review by AnoojNair — APPROVED** [review]
@aslotte Looks good..

**Comment by aslotte** [comment]
We'll need to set some env variables in the workflow file for the SQLite integration tests to run the end-to-end Kubernetes test
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv

**Comment by aslotte** [comment]
Currently remaining
- Add CLI command to clean up Kubernetes resources after deployment
- Update HTTP request to include payload to ensure successful response
- Update CI workflow to set env variables and test that it works
- Consolidate titanic data and models under test common folder if possible
- Add additional unit tests for getting external IP
- Add end-to-end test for deployment to URI with similar check to load the model and do a prediction

**Comment by aslotte** [comment]
@Brett-Parker  / @AnoojNair this PR is finally done! 🥳 
I added some additional issues for some additional functionality regarding Kubernetes deployments we want to include for v1.2, but this is a really big step in the right direction! I added an integration test that actually does end to end deploys it to a Kuberenetes Cluster in Azure (under my account) so that we can use that to automatically test that everything is working. The test is really cool as it actually trains a real model, deploys it to Kubernetes, and then we do an HTTP request with a valid ModelInput to make sure we get a response.

**Pull request merged**
