### PR TITLE
[WIP] Adding a MLOps.NET dotnet global tool 

### LINKED ISSUE #121: Add an MLOps.NET dotnet global tool
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be interesting to have a dotnet global tool for some of the functionality in MLOps.NET so it can be automated via the CLI. That could include various deployment scenarios. 

A dotnet global tool is a command line nuget package. This is a good reference: https://www.dotnetcurry.com/dotnet/1495/dotnet-core-global-tools

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by AnoojNair**
Fixes #121 

@aslotte , I have added a CLI project to the solution. Let me know your thoughts. Have added a few commands to 

create experiment, run. List runs, metrics and artifacts. Set datasource to cosmosdb etc.

Steps to install 

1. Run dotnet pack where the MLOPS.Net.CLI.csproj file exists.
2. From the same location run

 dotnet tool install --global --add-source ./nupkg mlops --version <version-number>

Commands 

1. Set Data source to CosmosDb

mlops  set-datasource  --datasource "CosmosDb"

2. Set endpoint and accountkey

mlops  config-cosmos --endpoint "https://localhost:8081" --accountkey "<key>"

3. Create experiment

mlops create-exp --name "test"

4. Create run

mlops create-run --exp-id "<experiment-id>"

5. mlops ls-runs --exp-name "test"

### CODE REVIEW

**Comment by aslotte** [comment]
This is a great start, I cloned the branch locally and took a deep look.

A couple of thoughts:
- I don't have too much experience with CLI tools, but given that no parameters are static, how does it store state, e.g. keys and the MLOpsContext?
- I think we'll need to both be able to configure the DataSource and the ModelRepository (currently only supports local file share). I think this may be possible to be part of the set-datasource method, and maybe the method can be 
`mlops set-storage-provider --model-repository BlobStorage --dataSource Cosmos`
'mlops set-storage-provider --model-repository S3 --dataSource SQLServer' etc.

**Comment by AnoojNair** [comment]
@aslotte , currently in order to store the keys it uses an appsettings,json file which is store under the .mlops folder under the users(same directory used as local model repo).

like the idea of setting the 2 providers using a single command. Will make that change.

**Comment by aslotte** [comment]
Gotcha, that makes a lot of sense! I think overall it looks really promising, I like it. I probably have a couple of comments on naming and structure. Do you want me to make those comments in this PR, or open a separate PR in your fork with the suggestions?

**Comment by AnoojNair** [comment]
@aslotte , Yes this PR was more of a draft . I like the idea of a separate PR on my fork to gather suggestions. Thank you. :)

**Comment by aslotte** [comment]
Great! I'll try to look at that later next week :)

**Comment by AnoojNair** [comment]
@aslotte i have pushed the changes to set data source and model repo using a single command.

set-storage-provider

**Comment by aslotte** [comment]
Excellent @AnoojNair - let me have a look.

**Comment by AnoojNair** [comment]
Opened a new PR https://github.com/aslotte/MLOps.NET/pull/329

**Pull request closed without merging**
