### PR TITLE
Update examples for 0.1.3-beta

### LINKED ISSUE #145: Update examples for 0.1.3-beta
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Update our existing examples to match 0.1.3-beta

### PR DESCRIPTION
**Pull request by Brett-Parker**
Updated all 3 examples to the latest released beta.

## Resolves
Fixes #145 

## Description
Updated the 3 examples to work with the latest released beta.

### CODE REVIEW

**Comment by Brett-Parker** [comment]
Ready for review @aslotte

**Comment by aslotte** [comment]
That's awesome @Brett-Parker, you're quickly becoming an expert! Would you mind adding some examples for some of the new features as well (if you feel comfortable doing that?)

E.g.:
- Logging Hyperparameters
- Logging confusion matrix (for the classifier)
- Setting training time

**Comment by Brett-Parker** [comment]
@aslotte Sure, I'll take a look today, may have some more questions :)

**Comment by Brett-Parker** [comment]
@aslotte feedback please :) Also caught a spelling mistake and a comment section with no comments.

**Comment by aslotte** [comment]
Thanks for the contribution!

**Pull request merged**
