### PR TITLE
Renamed to ModelContext

### LINKED ISSUE #59: Rename MLLifecycleManager to MLOpsContext
**Is your feature request related to a problem? Please describe.**
`MLLifecycleManager` is a mouthful. That's a problem.

**Describe the solution you'd like**
An easier term to understand and annunciate is `ModelContext` and `IModelContext`
As part of this issue, we would rename `MLLifecycleManager` to `ModelContext`

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by aslotte**
## Resolves
Fixes #59 

## Description
Renamed to ModelContext

### CODE REVIEW

**Comment by aslotte** [comment]
Other suggestions would be `LifeCycleManager` or keep as `MLLifeCycleManager`. I'm open for suggestions here. cc: @dcostea  @AnoojNair  @lqdev

**Comment by lqdev** [comment]
How about something about MLOpsContext. A play on the original MLContext, except it's more specific to the Ops side of it. ModelContext is good too since you're tracking the model lifecycle.

**Comment by aslotte** [comment]
I like that idea @lqdev - especially since the library is called MLOps.NET as well. @dcostea  / @AnoojNair  what do you think?

**Comment by AnoojNair** [comment]
What if the LifeCycleManager is an extension method on MLContext.

Something like this may be?

 var mlManager = mlContext.LifeCycleManager(connectionString);

**Comment by aslotte** [comment]
I like where you're going with that @AnoojNair. Given the numerous configuration options available to set up the manger properly, and the discussion on going in #70 it may make sense to keep them separate.

**Comment by AnoojNair** [comment]
> I like where you're going with that @AnoojNair. Given the numerous configuration options available to set up the manger properly, and the discussion on going in #70 it may make sense to keep them separate though.

Make sense it might be a loooooong call chain.  Happy with MLOpsContext.

**Comment by aslotte** [comment]
I'm closing this PR for now. I like the idea of renaming it to `MLOpsContext` and will open a new PR with that suggestion once the `MLOpsBuilder` PR has been merged.

**Pull request closed without merging**
