### PR TITLE
Created physical test and source folders to facilitate VS Code

### PR DESCRIPTION
**Pull request by aslotte**
## Resolves
No structure when opening the solution in Visual Studio

## Description
image

### CODE REVIEW

**Comment by aslotte** [comment]
@shanranm would this work for you?

**Comment by shanranm** [comment]
yes! anything that keeps the test projects is fine. 
Why not follow the [ml.net](https://github.com/dotnet/machinelearning) repo structure?

**Comment by aslotte** [comment]
That's a fair point, which would eliminate one folder. I'll have a look at it in the coming days.

**Comment by aslotte** [comment]
Closing in favor for #151

**Pull request closed without merging**
