### PR TITLE
Added a multi-class classification example

### LINKED ISSUE #91: Add multiclass classification example
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Added an example of multi-class classification

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by aslotte**
## Resolves
Fixes #91 

## Description
Added an initial example for multi-class classification using our latest MLOps.NET dependency and SQLite.

### CODE REVIEW

**Comment by aslotte** [comment]
This is ready for a review!

**Comment by shanranm** [comment]
I don't see MLOps.Net code, missed a commit?

**Comment by aslotte** [comment]
Great catch @shanranm - pushed latest commit

**Comment by AnoojNair** [comment]
Hi @aslotte 

Thank you for adding the examples solution. That would be really helpful. I ran it locally and for me the last step(saving model file) broke as i don't have the c:\mlops folder. I feel we should create if it does not exist.

Also, would be really helpful if we added console messages in the example , the fit takes a while and without any message on the console it seems as if something is wrong.
Let me know if you would like me to add 2 issues to address these?

**Comment by aslotte** [comment]
@AnoojNair thank you for running it! We didn't have time to do that during the stream :)
Totally agree, let me add comments for each step later so we know what's going on.

Regarding the C:\MLOps folder, totally agree, we should create it if it doesn't exist. Mind adding an issue for that? Thanks!

**Comment by AnoojNair** [comment]
Sure added #95  to address that.

**Pull request merged**
