### PR TITLE
[WIP - AJ's PR] Adding MLOps.NET.CLI

### PR DESCRIPTION
**Pull request by aslotte**

### CODE REVIEW

**Comment by aslotte** [comment]
@AnoojNair I was trying to open a PR against your branch but wasn't really successful so had to open a new PR. I had a look at the code and it's a great start! Did some clean-up as you can see in my latest commit, let me know what you think! 

The only remaining question I have is if it's possible to break the CommandHelper down into smaller classes?
E.g. `MLOpsBuilderCli`, `LifeCycleCatalogCli` and so forth as I think we'll continue to add new commands. 

Great work, and let me know how you want to proceed 😄

**Comment by AnoojNair** [comment]
@aslotte Thank you for the clean up. Lets continue with this PR. I have thinking about splitting up the CommandHelper. I will split them and push the changes.

**Comment by aslotte** [comment]
That's great @AnoojNair!

**Comment by AnoojNair** [comment]
@aslotte , i have pushed the changes.  Not sure if we would need a new PR as this PR is not reflecting the changes.

**Comment by aslotte** [comment]
Which branch did you push them too?

**Comment by AnoojNair** [comment]
i pushed my changes to the Issue121_CLI_Alex branch in upstream. I guess it would be easier if i start a new PR from my fork. Is that ok?

**Comment by aslotte** [comment]
Strange, that should have worked. Absolutely, feel free to open a new PR or whatever you think may help 👍

**Comment by AnoojNair** [comment]
Opened a new PR https://github.com/aslotte/MLOps.NET/pull/329

**Pull request closed without merging**
